### ISSUE TITLE
`modifyColumn` with reorg and positon get wrong result.

### ISSUE THREAD

**Issue by Defined2014** [tangenta/tidb#80]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table t;
create table t (a BIGINT NULL DEFAULT '-283977870758975838', b double);
insert into t values (-283977870758975838, 0);
alter table t change column a c tinyint null default '111' after b, modify column b time null default '13:51:02' FIRST;
show create table t;
```

### 2. What did you expect to see? (Required)

ddl failed and table not change.

### 3. What did you see instead (Required)

ddl failed but table also changed, or ban those SQLs.

### 4. What is your TiDB version? (Required)

found by #63

**Comment by Defined2014** [comment]
Seems it looks a cascading SQL. Do we need to ban it? Or we should support it? @tangenta

**Comment by tangenta** [comment]
I think "after b" is not cascading?
